local p = require('neg.palette')

return {
  BufferLineFill={bg=p.bg_default},
  BufferLineBackground={fg=p.fg_comment, bg=p.bg_default},
  BufferLineBufferSelected={fg=p.fg_default, bg=p.bg_cursorline, bold=true},
  BufferLineBufferVisible={fg=p.fg_default, bg=p.bg_default},
  BufferLineTab={fg=p.fg_comment, bg=p.bg_default},
  BufferLineTabSelected={fg=p.fg_default, bg=p.bg_cursorline, bold=true},
  BufferLineTabClose={fg=p.fg_red_blood, bg=p.bg_default},
  BufferLineIndicatorSelected={fg=p.fg_keyword_3, bg=p.bg_cursorline},
  BufferLineIndicatorVisible={fg=p.fg_keyword_3, bg=p.bg_default},
  BufferLineCloseButton={fg=p.fg_comment, bg=p.bg_default},
  BufferLineCloseButtonSelected={fg=p.fg_red_blood, bg=p.bg_cursorline},
  BufferLineCloseButtonVisible={fg=p.fg_comment, bg=p.bg_default},
  BufferLineModified={fg=p.fg_warning, bg=p.bg_default},
  BufferLineModifiedSelected={fg=p.fg_warning, bg=p.bg_cursorline},
  BufferLineModifiedVisible={fg=p.fg_warning, bg=p.bg_default},
  BufferLineDuplicate={fg=p.fg_comment, bg=p.bg_default},
  BufferLineDuplicateSelected={fg=p.fg_comment, bg=p.bg_cursorline},
  BufferLineDuplicateVisible={fg=p.fg_comment, bg=p.bg_default},
  BufferLineSeparator={fg=p.fg_dark, bg=p.bg_default},
  BufferLineSeparatorSelected={fg=p.fg_dark, bg=p.bg_cursorline},
  BufferLineSeparatorVisible={fg=p.fg_dark, bg=p.bg_default},
  BufferLineOffsetSeparator={fg=p.fg_dark, bg=p.bg_default},
}
