local p = require('neg.palette')

return {
  BufferLineFill={bg=p.bg_default},
  BufferLineBackground={fg=p.comment_color, bg=p.bg_default},
  BufferLineBufferSelected={fg=p.default_color, bg=p.bg_cursorline, bold=true},
  BufferLineBufferVisible={fg=p.default_color, bg=p.bg_default},
  BufferLineTab={fg=p.comment_color, bg=p.bg_default},
  BufferLineTabSelected={fg=p.default_color, bg=p.bg_cursorline, bold=true},
  BufferLineTabClose={fg=p.red_blood_color, bg=p.bg_default},
  BufferLineIndicatorSelected={fg=p.keyword3_color, bg=p.bg_cursorline},
  BufferLineIndicatorVisible={fg=p.keyword3_color, bg=p.bg_default},
  BufferLineCloseButton={fg=p.comment_color, bg=p.bg_default},
  BufferLineCloseButtonSelected={fg=p.red_blood_color, bg=p.bg_cursorline},
  BufferLineCloseButtonVisible={fg=p.comment_color, bg=p.bg_default},
  BufferLineModified={fg=p.warning_color, bg=p.bg_default},
  BufferLineModifiedSelected={fg=p.warning_color, bg=p.bg_cursorline},
  BufferLineModifiedVisible={fg=p.warning_color, bg=p.bg_default},
  BufferLineDuplicate={fg=p.comment_color, bg=p.bg_default},
  BufferLineDuplicateSelected={fg=p.comment_color, bg=p.bg_cursorline},
  BufferLineDuplicateVisible={fg=p.comment_color, bg=p.bg_default},
  BufferLineSeparator={fg=p.dark_color, bg=p.bg_default},
  BufferLineSeparatorSelected={fg=p.dark_color, bg=p.bg_cursorline},
  BufferLineSeparatorVisible={fg=p.dark_color, bg=p.bg_default},
  BufferLineOffsetSeparator={fg=p.dark_color, bg=p.bg_default},
}
