local p = require('neg.palette')

return {
  CmpItemKindDefault={fg=p.cmp_default_color, bg='NONE'},
  CmpItemKindFunction={fg=p.red_blood_color, bg='NONE'},
  CmpItemKindInterface={fg=p.keyword3_color, bg='NONE'},
  CmpItemKindKeyword={fg=p.literal3_color, bg='NONE'},
  CmpItemKindMethod={fg=p.red_blood_color, bg='NONE'},
  CmpItemKindProperty={fg=p.literal3_color, bg='NONE'},
  CmpItemKindVariable={fg=p.keyword3_color, bg='NONE'},
  -- Extended kinds
  CmpItemKindText={fg=p.default_color, bg='NONE'},
  CmpItemKindClass={fg=p.keyword2_color, bg='NONE'},
  CmpItemKindModule={fg=p.preproc_dark_color, bg='NONE'},
  CmpItemKindField={fg=p.identifier_color, bg='NONE'},
  CmpItemKindConstructor={fg=p.function_color, bg='NONE'},
  CmpItemKindEnum={fg=p.preproc_light_color, bg='NONE'},
  CmpItemKindUnit={fg=p.literal2_color, bg='NONE'},
  CmpItemKindValue={fg=p.literal3_color, bg='NONE'},
  CmpItemKindEnumMember={fg=p.literal2_color, bg='NONE'},
  CmpItemKindConstant={fg=p.literal2_color, bg='NONE'},
  CmpItemKindStruct={fg=p.keyword2_color, bg='NONE'},
  CmpItemKindEvent={fg=p.violet_color, bg='NONE'},
  CmpItemKindOperator={fg=p.keyword2_color, bg='NONE'},
  CmpItemKindTypeParameter={fg=p.keyword2_color, bg='NONE'},
  CmpItemKindSnippet={fg=p.string_color, bg='NONE'},
  CmpItemKindColor={fg=p.violet_color, bg='NONE'},
  CmpItemKindFile={fg=p.include_color, bg='NONE'},
  CmpItemKindReference={fg=p.tag_color, bg='NONE'},
  CmpItemKindFolder={fg=p.include_color, bg='NONE'},
}
