local p = require('neg.palette')

-- Treesitter + LSP semantic token links
return {
  -- Core language captures: set explicit styles to avoid relying on builtins
  -- TS-only comments styling (do not depend on legacy Comment group)
  ['@comment']={ fg = p.comment_color, italic = true },
  ['@keyword']={ fg = p.keyword2_color },
  ['@keyword.function']={ fg = p.keyword1_color },
  ['@keyword.operator']={ fg = p.keyword2_color },
  ['@type']={ fg = p.keyword2_color },
  ['@type.builtin']={ fg = p.keyword3_color },
  ['@function']={ fg = p.function_color },
  ['@function.call']={ link = '@function' },
  ['@method']={ link = '@function' },
  ['@method.call']={ link = '@function' },
  ['@constant']={ fg = p.literal2_color },
  ['@string']={ fg = p.string_color },
  ['@number']={ fg = p.keyword1_color },
  ['@boolean']={ fg = p.literal3_color },
  ['@operator']={ fg = p.keyword2_color },
  -- Operator families with subtle per-family hues
  -- assignment: dark/neutral
  ['@operator.assignment']={ fg = p.keyword4_color },
  ['@operator.assignment.compound']={ fg = p.keyword4_color },
  ['@operator.assignment.augmented']={ fg = p.keyword4_color },
  -- comparison: strong blue
  ['@operator.comparison']={ fg = p.keyword3_color },
  ['@operator.comparison.equality']={ fg = p.keyword3_color },
  ['@operator.comparison.relational']={ fg = p.keyword3_color },
  -- arithmetic: lighter accent
  ['@operator.arithmetic']={ fg = p.keyword1_color },
  ['@operator.arithmetic.add']={ fg = p.keyword1_color },
  ['@operator.arithmetic.sub']={ fg = p.keyword1_color },
  ['@operator.arithmetic.mul']={ fg = p.keyword1_color },
  ['@operator.arithmetic.div']={ fg = p.keyword1_color },
  ['@operator.arithmetic.mod']={ fg = p.keyword1_color },
  ['@operator.arithmetic.pow']={ fg = p.keyword1_color },
  -- logical: teal
  ['@operator.logical']={ fg = p.keyword2_color },
  ['@operator.logical.and']={ fg = p.keyword2_color },
  ['@operator.logical.or']={ fg = p.keyword2_color },
  ['@operator.logical.not']={ fg = p.keyword2_color },
  ['@operator.logical.xor']={ fg = p.keyword2_color },
  -- bitwise: delimiter tone
  ['@operator.bitwise']={ fg = p.delimiter_color },
  ['@operator.bitwise.and']={ fg = p.delimiter_color },
  ['@operator.bitwise.or']={ fg = p.delimiter_color },
  ['@operator.bitwise.xor']={ fg = p.delimiter_color },
  ['@operator.bitwise.shift']={ fg = p.delimiter_color },
  ['@operator.bitwise.not']={ fg = p.delimiter_color },
  ['@operator.bitwise.left_shift']={ fg = p.delimiter_color },
  ['@operator.bitwise.right_shift']={ fg = p.delimiter_color },
  -- others
  ['@operator.ternary']={ fg = p.keyword3_color },
  ['@operator.unary']={ fg = p.keyword4_color },
  ['@operator.increment']={ fg = p.keyword1_color },
  ['@operator.decrement']={ fg = p.keyword1_color },
  ['@operator.range']={ fg = p.delimiter_color },
  ['@operator.spread']={ fg = p.delimiter_color },
  ['@operator.pipe']={ fg = p.delimiter_color },
  ['@operator.arrow']={ fg = p.keyword1_color },
  ['@operator.coalesce']={ fg = p.keyword3_color },
  ['@namespace']={ fg = p.identifier_color },
  ['@parameter']={ fg = p.identifier_color },
  ['@variable']={ fg = p.variable_color },
  ['@variable.parameter']={link='@parameter'},
  ['@variable.member']={link='@field'},
  ['@module']={link='@namespace'},
  ['@number.float']={link='@float'},
  ['@string.special.symbol']={link='@symbol'},
  ['@string.regexp']={link='@string.regex'},
  ['@variable.builtin']={ fg = p.identifier_color, italic = true },
  ['@type.definition']={ link = '@type' },
  -- explicit anchors for linked captures above
  ['@float']={ fg = p.literal3_color },
  ['@symbol']={ fg = p.literal2_color },
  ['@string.regex']={ fg = p.string_color },

  -- Additional common captures
  ['@attribute']={ fg = p.identifier_color },
  ['@attribute.builtin']={ link='@attribute' },
  ['@constructor']={ link='@function' },
  ['@constant.builtin']={ link='@constant' },
  ['@function.builtin']={ link='@function' },
  ['@function.macro']={ fg = p.function_color },
  ['@property']={ fg = p.identifier_color },
  ['@field']={ fg = p.identifier_color },
  ['@punctuation.bracket']={ fg = p.delimiter_color },
  ['@punctuation.delimiter']={ fg = p.delimiter_color },
  ['@string.escape']={ fg = p.literal2_color },
  ['@string.special.url']={ underline = true, fg = p.keyword4_color },
  ['@character']={ fg = p.string_color },
  ['@character.special']={ link = '@character' },
  -- number specializations
  ['@number.integer']={ link = '@number' },
  ['@number.hex']={ link = '@number' },
  ['@number.octal']={ link = '@number' },
  ['@number.binary']={ link = '@number' },

  -- Additional markup helpers
  ['@string.special']={link='@markup.link.label'},
  ['@string.special.path']={link='@string.special'},
  ['@punctuation.special']={ fg = p.delimiter_color },

  -- Markup base styles (TS-only)
  ['@markup.strong']={ bold = true },
  ['@markup.italic']={ italic = true },
  ['@markup.underline']={ underline = true },
  ['@markup.strikethrough']={ strikethrough = true },
  ['@markup.heading']={ bold = true },
  ['@markup.heading.1']={ link='@markup.heading' },
  ['@markup.heading.2']={ link='@markup.heading' },
  ['@markup.heading.3']={ link='@markup.heading' },
  ['@markup.heading.4']={ link='@markup.heading' },
  ['@markup.heading.5']={ link='@markup.heading' },
  ['@markup.heading.6']={ link='@markup.heading' },
  ['@markup.quote']={ fg = p.comment_color, italic = true },
  ['@markup.link']={ underline = true },
  -- URLs are underlined and use include_color to avoid oversaturation
  ['@markup.link.url']={ underline = true, fg = p.include_color },
  ['@markup.link.label']={ underline = true },
  ['@markup.raw']={ fg = p.string_color },
  ['@markup.raw.block']={ fg = p.string_color },
  ['@markup.raw.inline']={ link='@markup.raw' },
  ['@markup.list']={ fg = p.comment_color },
  ['@markup.list.checked']={ fg = p.identifier_color },
  ['@markup.list.unchecked']={ fg = p.comment_color },
  ['@markup.list.numbered']={ fg = p.comment_color },
  -- Additional markup scopes (core kept minimal; extra variants in treesitter_extras)

  -- Helix captures
  ['@function.method']={link='@method'},
  ['@function.method.call']={link='@method.call'},

  -- Comment severities
  ['@comment.todo']={ fg = p.preproc_light_color },
  ['@comment.warning']={ fg = p.warning_color },
  ['@comment.error']={ fg = p.diff_delete_color },
  ['@comment.note']={ fg = p.identifier_color },
  ['@comment.documentation']={ fg = p.comment_color, italic = true },

  -- Diff groups
  ['@diff.plus']={ fg = p.diff_add_color },
  ['@diff.minus']={ fg = p.diff_delete_color },
  ['@diff.delta']={ fg = p.diff_change_color },

  -- Keyword families
  ['@keyword.directive']={link='@preproc'},
  ['@keyword.storage']={link='@storageclass'},
  ['@keyword.conditional']={link='@conditional'},
  ['@keyword.debug']={link='@debug'},
  ['@keyword.exception']={link='@exception'},
  ['@keyword.import']={link='@include'},
  ['@keyword.repeat']={link='@repeat'},
  ['@keyword.operator']={link='@operator'},
  ['@keyword.return']={link='@keyword'},

  -- Preprocessor/keywords (explicit TS targets)
  ['@preproc']={ fg = p.preproc_light_color },
  ['@define']={ fg = p.preproc_dark_color },
  ['@include']={ fg = p.include_color },
  ['@macro']={ link='@function.macro' },
  ['@constant.macro']={ link='@macro' },
  ['@conditional']={ fg = p.keyword1_color },
  ['@repeat']={ fg = p.keyword1_color },
  ['@label']={ fg = p.keyword3_color },
  ['@exception']={ fg = p.red_blood_color },
  ['@storageclass']={ fg = p.keyword1_color },
  ['@type.qualifier']={ link='@keyword' },
  ['@type.parameter']={ link='@type' },

  -- HTML/XML-like tags
  ['@tag']={ fg = p.tag_color },
  ['@tag.delimiter']={ fg = p.keyword2_color },
  ['@tag.attribute']={ fg = p.identifier_color },
  ['@module.builtin']={ link='@module' },

  -- LSP semantic tokens
  ['@lsp.type.class']={link='@type'},
  ['@lsp.type.struct']={link='@type'},
  ['@lsp.type.interface']={link='@type'},
  ['@lsp.type.enum']={link='@type'},
  ['@lsp.type.type']={link='@type'},
  ['@lsp.type.typeAlias']={link='@type.definition'},
  ['@lsp.type.typeParameter']={link='@type'},
  ['@lsp.type.namespace']={link='@namespace'},
  ['@lsp.type.parameter']={link='@parameter'},
  ['@lsp.type.variable']={link='@variable'},
  ['@lsp.type.property']={link='@property'},
  ['@lsp.type.enumMember']={link='@constant'},
  ['@lsp.type.function']={link='@function'},
  ['@lsp.type.macro']={link='@function.macro'},
  ['@lsp.type.method']={link='@method'},
  ['@lsp.type.event']={link='@type'},
  ['@lsp.type.operator']={link='@operator'},
  ['@lsp.type.modifier']={link='@keyword'},
  ['@lsp.type.builtinType']={link='@type.builtin'},
  ['@lsp.type.comment']={link='@comment'},
  ['@lsp.type.string']={link='@string'},
  ['@lsp.type.boolean']={link='@boolean'},
  ['@lsp.type.number']={link='@number'},
  ['@lsp.type.regexp']={link='@string.regex'},
  ['@lsp.type.escapeSequence']={link='@string.escape'},
  ['@lsp.type.formatSpecifier']={link='@string.special'},

  -- LSP modifiers
  ['@lsp.typemod.variable.readonly']={link='@constant'},
  ['@lsp.typemod.variable.global']={link='@constant'},
  ['@lsp.typemod.variable.static']={link='@constant'},
  ['@lsp.typemod.variable.defaultLibrary']={link='@variable.builtin'},
  ['@lsp.typemod.function.defaultLibrary']={link='@function.builtin'},
  ['@lsp.typemod.method.defaultLibrary']={link='@function.builtin'},
  ['@lsp.typemod.class.defaultLibrary']={link='@type.builtin'},
  ['@lsp.typemod.macro.defaultLibrary']={link='@function.macro'},
  ['@lsp.typemod.enum.defaultLibrary']={link='@type.builtin'},
  ['@lsp.typemod.type.defaultLibrary']={link='@type.builtin'},
  ['@lsp.typemod.deprecated']={ strikethrough = true, fg = p.comment_color },
  -- extra common modifiers
  -- declaration variants moved to extras
  ['@lsp.typemod.variable.definition']={link='@variable'},
  ['@lsp.typemod.variable.reference']={link='@variable'},
  ['@lsp.typemod.parameter.readonly']={link='@parameter'},
  ['@lsp.typemod.property.readonly']={link='@constant'},
  ['@lsp.typemod.method.static']={link='@method'},
  -- additional static/abstract/readonly moved to extras
  ['@lsp.typemod.function.async']={link='@function'},
  ['@lsp.typemod.keyword.async']={link='@keyword'},
}
